-- 고양이와 개는 몇 마리 있을까

SELECT ANIMAL_TYPE, COUNT(*)
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;

-- 동명 동물 수 찾기

SELECT NAME, COUNT(*) as count
FROM ANIMAL_INS
GROUP BY NAME
HAVING count >= 2 AND NAME IS NOT NULL
ORDER BY NAME;

-- 입양 시각 구하기(1)

SELECT DATE_FORMAT(DATETIME,'%H') as HOUR, COUNT(*)
FROM ANIMAL_OUTS
GROUP BY DATE_FORMAT(DATETIME,'%H')
HAVING HOUR >= 9 AND HOUR < 20
ORDER BY DATE_FORMAT(DATETIME,'%H');

-- 입양 시각 구하기(2)

WITH RECURSIVE CTE AS (
        SELECT 0 AS H
        UNION ALL
        SELECT H+1 FROM CTE WHERE H < 23
)

SELECT cast(H as unsigned) AS HOUR, COUNT(*) -1 AS COUNT
FROM (
    SELECT DATE_FORMAT(DATETIME,'%H') AS H FROM ANIMAL_OUTS
    UNION ALL
    SELECT * FROM CTE
) Y1
GROUP BY HOUR
ORDER BY HOUR;
